routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/contatos', 'ContatoController@showContactsToGuest')->name('contato.convidados');
Route::middleware(['auth'])->group(function () {
    Route::resource("contato","ContatoController");
});

app/Contato.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Contato extends Model
{
    use SoftDeletes;
    protected $dates = ['deleted_at'];

    protected $fillable = [
        'nome',
        'contato',
        'email'
    ];

}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ContatoController.php
<?php

namespace App\Http\Controllers;

use App\Contato;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Response;
use DB;
use Illuminate\Support\Facades\Log;
Use Alert;
class ContatoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $contatos = Contato::paginate(10);

        return view('contato.index')->with("contatos", $contatos);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('contato.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nome' => 'required|string|min:6|max:255',
            'contato' => 'required|string|max:9|unique:contatos',
            'email' => 'nullable|email|max:255|unique:contatos'
        ]);

        DB::beginTransaction();
        try{
           
            $contato = Contato::create($request->all());
            DB::commit();
            Alert::success("Contato criada com sucesso");
            return redirect()->route('contato.index');
        }
        catch(\Exception $e){            
            DB::rollback();
            Log::error('Falha ao criar contato '.$e->getCode()." Msg: ".$e->getMessage());
            return abort('500');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Contato  $contato
     * @return \Illuminate\Http\Response
     */
    public function show(Contato $contato)
    {
        return view('contato.show', compact('contato'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Contato  $contato
     * @return \Illuminate\Http\Response
     */
    public function edit(Contato $contato)
    {
        return view('contato.edit', compact('contato'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Contato  $contato
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Contato $contato)
    {
        $request->validate([
            'nome' => 'required|string|min:6|max:255',
            'contato' => [
                'required',
                'string',
                'max:9',
                \Illuminate\Validation\Rule::unique('contatos')->ignore($contato->id)
            ],
            'email' => [
                'email',
                'max:255',
                \Illuminate\Validation\Rule::unique('contatos')->ignore($contato->id)
            ]
        ]);

        DB::beginTransaction();
        try{
           
            $contato->update($request->all());

            DB::commit();
            Alert::success("Contato editado com sucesso");
            return redirect()->route('contato.index');
        }
        catch(\Exception $e){            
            DB::rollback();
            Log::error('Falha ao criar Contato '.$e->getCode()." Msg: ".$e->getMessage());
            return abort('500');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Contato  $contato
     * @return \Illuminate\Http\Response
     */
    public function destroy(Contato $contato)
    {
        DB::beginTransaction();
        try{
            
            $contato->delete();
            DB::commit();

            Alert::success("Contato removido com sucesso");
            return redirect()->route('contato.index');
        }
        catch(\Exception $e){            
            DB::rollback();
            Log::error('Falha ao apagaar contato '.$e->getCode()." Msg: ".$e->getMessage());
            return abort('500');
        }
    }

    public function showContactsToGuest(Request $request){
        $contatos = Contato::paginate(10);

        return view('contato.convidados')->with("contatos", $contatos);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/contato/convidados.blade.php
@extends('layouts.app')

@section('content')
<div class="card">
    <div class="card-header">Contatos</div>
    <div class="card-body">
    <h2>Veja os contatos</h2>
        <table class="table">
            <thead class="">
              <tr>
                <th scope="col">ID</th>
                <th scope="col">Nome</th>
                <th scope="col">Contato</th>
                <th scope="col">Email</th>
              </tr>
            </thead>
            <tbody>
                @foreach($contatos as $contato) 
                <tr>
                    <td>{{$contato->id}}</td>
                    <td>{{$contato->nome}}</td>
                    <td>{{$contato->contato}}</td>
                    <td>{{$contato->email}}</td>
                </tr>
                @endforeach
            </tbody>
            <tfoot>
                <tr>{{ $contatos->links() }}</tr>
            </tfoot>
        </table>
    </div>
</div>
@endsection

resources/views/contato/create.blade.php
@extends('layouts.app')

@section('content')
<div class="card">
    <div class="card-header">Criar Contato</div>
    <div class="card-body">
    <a class="" href="{{route('contato.index')}}">
        Voltar para lista
    </a>
    
    <form method="POST" action="{{ route('contato.store') }}" accept-charset="UTF-8" enctype="multipart/form-data" class="mt-3">
        @csrf

        @include("contato.form")

        <div class="text-center">
            <button type="submit" class="btn btn-success"><i class="fas fa-save"></i> Salvar</button>
            <a href="{{ route('contato.index') }}" class="btn btn-danger"><i class="fas fa-arrow-left"></i> Voltar</a>
        </div>
    </form>
    </div>
</div>
@endsection

resources/views/contato/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="card">
    <div class="card-header">Editar Contato</div>
    <div class="card-body">
    <a class="" href="{{route('contato.index')}}">
        Voltar para lista
    </a>
    <div class="h-100"></div>
    <form method="POST" class="d-inline" action="{{route('contato.destroy',$contato->id)}}">
        @csrf
        @method('DELETE')
        <button class="btn btn-danger">Excluir</button>
    </form>
    <form method="POST" action="{{ route('contato.update', $contato->id) }}" accept-charset="UTF-8" enctype="multipart/form-data" class="mt-3">
        @csrf
        @method('PUT')
        @include("contato.form")

        <div class="text-center">
            <button type="submit" class="btn btn-success"><i class="fas fa-save"></i> Salvar</button>
            <a href="{{ route('contato.index') }}" class="btn btn-danger"><i class="fas fa-arrow-left"></i> Voltar</a>
        </div>
    </form>
    </div>
</div>
@endsection

resources/views/contato/form.blade.php
<div class="row">
    @csrf
    <div class="col-md-12">
        <div class="form-group">
            <label for="nome" class="control-label">Nome</label>
            <input id="nome" type="text" class="form-control @error('nome')is-invalid @enderror" name="nome" value="{{ old('nome') ?? $contato->nome ?? '' }}" required autofocus>
            @error('nome')
                <div style="color: red;" role="alert">
                    <strong>{{ $message }}</strong>
                </div>
            @enderror
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
            <label for="contato" class="control-label">Contato</label>
            <input id="contato" type="text" class="form-control  @error('contato')is-invalid @enderror" name="contato" value="{{ old('contato') ?? $contato->contato ?? '' }}" required maxlength="9">
            @error('contato')
                <div style="color: red;" role="alert">
                    <strong>{{ $message }}</strong>
                </div>
            @enderror
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
            <label for="email" class="control-label">Email</label>
            <input id="email" type="email" class="form-control @error('email')is-invalid @enderror" name="email" value="{{ old('email') ?? $contato->email ?? '' }}">
            @error('email')
                <div style="color: red;" role="alert">
                    <strong>{{ $message }}</strong>
                </div>
            @enderror
        </div>
    </div>
</div>

resources/views/contato/index.blade.php
@extends('layouts.app')

@section('content')
<div class="card">
    <div class="card-header">Contatos</div>
    <div class="card-body">
    <a class="btn btn-primary mb-4" href="{{route('contato.create')}}">
        <i class="fa fa-plus"></i>
        Adicionar
    </a>
    <h2>Veja, edite e remova os contatos</h2>
        <table class="table">
            <thead class="">
              <tr>
                <th scope="col">ID</th>
                <th scope="col">Nome</th>
                <th scope="col">Contato</th>
                <th scope="col">Email</th>
                <th scope="col">Ações</th>
              </tr>
            </thead>
            <tbody>
                @foreach($contatos as $contato) 
                <tr>
                    <td>{{$contato->id}}</td>
                    <td>{{$contato->nome}}</td>
                    <td>{{$contato->contato}}</td>
                    <td>{{$contato->email}}</td>
                    <td>
                        <a href="{{route('contato.show', $contato->id)}}" class="btn btn-secondary" title="Editar contato">Ver Detalhes</a>
                        <a href="{{route('contato.edit', $contato->id)}}" class="btn btn-success" title="Editar contato">Editar</a>
                        <form class="d-inline" method="POST" action="{{route('contato.destroy',$contato->id)}}">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger">Excluir</button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
            <tfoot>
                <tr>{{ $contatos->links() }}</tr>
            </tfoot>
        </table>
    </div>
</div>
@endsection

resources/views/contato/show.blade.php
@extends('layouts.app')

@section('content')
<div class="card">
    <div class="card-header">Ver Contato</div>
    <div class="card-body">
    <a class="" href="{{route('contato.index')}}">
        Voltar para lista
    </a>
    <div class="h-100"></div>
    <a class="btn btn-success" href="{{route('contato.edit', $contato->id)}}">
        Editar
    </a>
    <form method="POST" class="d-inline" action="{{route('contato.destroy',$contato->id)}}">
        @csrf
        @method('DELETE')
        <button class="btn btn-danger">Excluir</button>
    </form>
    <div class="row mt-4">
        <div class="col-6">
            <h2><b>Criado em</b></h2>
            <h3>{{$contato->created_at}}</h3>
        </div>
        <div class="col-6">
            <h2><b>Atualizado em</b></h2>
            <h3>{{$contato->updated_at}}</h3>
        </div>
        <div class="col-12">
            <h2><b>Nome do Contato</b></h2>
            <h3>{{$contato->nome}}</h3>
        </div>
        <div class="col-12">
            <h2><b>Contato</b></h2>
            <h3>{{$contato->contato}}</h3>
        </div>
        <div class="col-12">
            <h2><b>Email</b></h2>
            <h3>{{$contato->email}}</h3>
        </div>
    </div>
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <p>Voce está logado!</p>
                    <a href="{{route('contato.index')}}">Ver lista de Contatos</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
@include('sweetalert::alert')
</html>